# defaults file
---
keepalived_install_method: native
keepalived_git_repo: https://github.com/acassen/keepalived.git
keepalived_version: v2.2.2
keepalived_install: []
keepalived_configure_options: []
keepalived_options: []

keepalived_ip_nonlocal_bind: '1'

keepalived_create_keepalived_script_user: False

keepalived_global_defs_notification_email:
  - 'root@localhost.localdomain'
keepalived_global_defs_notification_email_from: 'root@localhost.localdomain'
keepalived_global_defs_smtp_server: '127.0.0.1'
keepalived_global_defs_smtp_connect_timeout: 30

keepalived_vrrp_script_map: {}

keepalived_vrrp_scripts: {}
keepalived_vrrp_track_processes: {}
keepalived_vrrp_sync_groups: {}

keepalived_vrrp_instances: {}

master_hostname: hap-keep-1

your_keepalived_configuration_file: files/keepalived.conf.j2
